### ISSUE TITLE
Please add a disclaimer to the Okta library

### ISSUE THREAD

**Issue by bretterer** [oxidecomputer/third-party-api-clients#80]
Hello,  I am requesting that you add a disclaimer to the Okta library stating that this is not an officially supported library by the Okta team.

ie:
> Okta is a registered trademark of Okta, Inc. and this tool has no affiliation with or sponsorship by Okta, Inc.

Thank you
Brian Retterer
Okta Developer Community Products Manager

**Comment by augustuswm** [comment]
Happy to get this added. I'll have that in in the next couple days.

**Comment by bretterer** [comment]
Perfect... Thank you so much for doing this.

**Comment by augustuswm** [comment]
Forgot to reply that this had been completed. There is a disclaimer now at the top of the GitHub readme and crates.io page.
