### ISSUE TITLE
Google Calendar: Question about extendedProperties field

### ISSUE THREAD

**Issue by NYBACHOK** [oxidecomputer/third-party-api-clients#84]
I need to store some information about event and `extendedProperties` field looks like what I wan't but  `Shared` object doesn't have any field so how I should store non visible to users information about event?

**Comment by joehoyle** [comment]
it looks like maybe this isn't supported? Did you find a way @NYBACHOK

**Comment by NYBACHOK** [comment]
@joehoyle Not realy. For my purposes I use `id` which is writable. I creating sha256 from data that I need to store.

**Comment by joehoyle** [comment]
@NYBACHOK ahh cool, didn't know that was a field! As it happens I cloned / forked this and make `extendedProperties.shared` a hashmap which looked to have worked.

**Comment by NYBACHOK** [comment]
@joehoyle I chose the easier way.
